### ISSUE TITLE
Include social icons

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/HarmonyCode#5] opened 2023-10-02 15:16 UTC
Include social icons such as instagram, twitter in the footer of the page

**Comment by Aabiskar-dhenga** [comment] 2023-10-03 14:45
hey dhanush can you elaborate where i should put social media icons >??

**Comment by DhanushNehru** [comment] 2023-10-03 14:51
HI @Aabiskar-dhenga in the footer, but i think @Mirthhh08 is already working on it

**Comment by Mirthhh08** [comment] 2023-10-03 14:57
![image](https://github.com/DhanushNehru/HarmonyCode/assets/92306499/ac24b495-78d9-4b6b-bbb5-414e79bbf4bf)
![image](https://github.com/DhanushNehru/HarmonyCode/assets/92306499/3fcb5c32-7d3b-46f3-b28c-5d247bc2c911)

Done with the work. A small request please add hacktoberfestaccepted tag .

**Comment by Mirthhh08** [comment] 2023-10-03 14:58
if you want any changes please let me know!!

**Comment by DhanushNehru** [comment] 2023-10-03 15:05
Can the 'Made with'  sentence be in the left itself. And only the social icons in the middle @Mirthhh08

**Comment by Mirthhh08** [comment] 2023-10-03 16:01
![image](https://github.com/DhanushNehru/HarmonyCode/assets/92306499/7cc9f4b3-1e16-4045-a27c-bc355b90f426)
Please check it ones and then I'll raise the pull request

**Comment by DhanushNehru** [comment] 2023-10-03 16:12
Hey @Mirthhh08 can you pull the latest code , as we have a share to social media in the footer .

Hope that doesn't collide

**Comment by Mirthhh08** [comment] 2023-10-03 16:14
yeahh sure!!

**Comment by DhanushNehru** [comment] 2023-10-03 16:51
Once done please raise a PR @Mirthhh08

**Comment by dhanyadgowda** [comment] 2024-10-02 19:52
Hey @DhanushNehru if the issue is still there can u assign it to me

**Closed** 2024-10-03 05:26 UTC
Labels: enhancement, help wanted, good first issue
